// Generated by scripts/gen_import_stubs.py from docs/kernel-imports.txt.
// Do not edit by hand: regenerate.
//
// One stub per kernel import that does not have a real implementation yet.
// Each reports itself and stops the process. To implement one: write it in the
// kernel_*.cpp file for its area, add its name to implemented_imports.txt, and
// regenerate. Running the game then tells you the next one it needs.
//
// PPC_FUNC, not PPC_FUNC_IMPL: ppc_recomp_shared.h declares the __imp__ name
// of an import with C++ linkage, and a definition has to match that. The
// PPC_FUNC_IMPL form is for recompiled guest functions, whose __imp__ symbol
// is a separate C linkage name behind an alias.
#include "kernel.h"


