# d3d_api.py: the Xbox 360 D3D library the title links in, as a table.
#
# The library is the range 0x822E0000..0x82300000 of default.xex. This lists
# every function in it that the game calls from outside the range (the API
# the port has to take over at the D3D level), with its size, how many call
# sites and callers it has outside, which PM4 packets it writes, which offsets
# of its first argument it reads and writes (for a device function, the
# device's fields), and the name given in NAMES once known.
#
#   python scripts/d3d_api.py [--markdown docs/d3d-api.md]
import re, glob, sys, os
from collections import defaultdict, Counter

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LO, HI = 0x822E0000, 0x82300000

# Names found so far, by what the function does (docs/native-d3d11-plan.md).
NAMES = {
    0x822F3620: 'draw indexed (DRAW_INDX, ~45 a frame)',
    0x822F3EA0: 'draw indexed, a variant (DRAW_INDX)',
    0x822F4338: 'draw indexed, a variant (DRAW_INDX)',
    0x822F6858: 'draw immediate (DRAW_INDX_2)',
    0x822EFFF0: 'rectangle draw with an event: clear or resolve (DRAW_INDX_2)',
    0x822FB4B0: 'shader load (IM_LOAD)',
    0x822F6430: 'fence (EVENT_WRITE_SHD)',
    0x822EC358: 'set the vertical blank callback (device+15120)',
    0x822F4A10: 'swap: the presentation countdown',
    0x822F1918: 'interrupt: vertical blank and command processor',
    0x822F16A0: 'wait for the GPU before a pool is reused',
    0x822EB950: 'get a surface description',
    0x822F3A28: 'THE draw: ~890 calls a frame, from the four worker threads',
    0x822F30F0: 'draw (~48 a frame)',
    0x822F6DF8: 'draw (with 822F6858, ~8 a frame)',
    0x822F8590: 'indirect buffer, predicated (INDIRECT_BUFFER)',
    0x822F1E68: 'write recorded buffers to the ring (the replay thread)',
    0x822F2818: 'kick the current segment to the GPU',
    0x82302A90: 'the replay thread: its run over the queue',
    0x82302DB0: 'begin recording a command buffer',
    0x82302E88: 'end recording a command buffer',
    0x822EC168: 'one turn of the wait for the GPU',
}

OPS = {0x22: 'DRAW_INDX', 0x36: 'DRAW_INDX_2', 0x27: 'IM_LOAD', 0x2B: 'IM_LOAD_IMMEDIATE', 0x2D: 'SET_CONSTANT',
       0x2F: 'LOAD_ALU_CONSTANT', 0x3F: 'INDIRECT_BUFFER', 0x3C: 'WAIT_REG_MEM', 0x46: 'EVENT_WRITE',
       0x58: 'EVENT_WRITE_SHD', 0x60: 'SET_BIN_MASK_LO', 0x61: 'SET_BIN_MASK_HI', 0x62: 'SET_BIN_SELECT_LO',
       0x63: 'SET_BIN_SELECT_HI', 0x64: 'SWAP', 0x57: 'MEM_WRITE', 0x45: 'COND_WRITE'}

def load():
    fr = re.compile(r'^PPC_FUNC_IMPL\(__imp__sub_([0-9A-F]{8})\)')
    ir = re.compile(r'^\s*// (\S+)\s*(.*)$')
    code = {}
    cur = None
    for p in sorted(glob.glob(os.path.join(ROOT, 'CoD3RecompLib', 'ppc', 'ppc_recomp.*.cpp'))):
        for line in open(p, encoding='utf-8', errors='replace'):
            m = fr.match(line)
            if m:
                cur = int(m.group(1), 16); code[cur] = []; continue
            m = ir.match(line)
            if m and cur is not None and not m.group(1).startswith('loc_'):
                code[cur].append((m.group(1), m.group(2).replace(' ', '')))
    return code

def main():
    code = load()
    callers = defaultdict(Counter)
    for f, body in code.items():
        for op, a in body:
            if op == 'bl' and a.startswith('0x'):
                callers[int(a, 16)][f] += 1
    rows = []
    for f in sorted(code):
        if not (LO <= f < HI): continue
        outside = Counter({c: n for c, n in callers[f].items() if not (LO <= c < HI)})
        if not outside: continue
        body = code[f]
        packets = set(); reads = Counter(); writes = Counter()
        hi = {}
        for op, a in body:
            m = re.match(r'r(\d+),(-?\d+)$', a)
            if op == 'lis' and m: hi[m.group(1)] = int(m.group(2)) & 0xFFFF
            m = re.match(r'r(\d+),r(\d+),(\d+)$', a)
            if op == 'ori' and m and m.group(2) in hi and hi[m.group(2)] in (0xC000, 0xC001, 0xC002, 0xC003, 0xC004, 0xC005, 0xC006, 0xC007, 0xC008):
                opcode = (int(m.group(3)) >> 8) & 0xFF
                if opcode in OPS: packets.add(OPS[opcode] + (' (pred)' if int(m.group(3)) & 1 else ''))
            m = re.match(r'r\d+,(-?\d+)\(r3\)$', a)
            if m:
                if op.startswith('l'): reads[int(m.group(1))] += 1
                elif op.startswith('st'): writes[int(m.group(1))] += 1
        rows.append((f, len(body), sum(outside.values()), len(outside), sorted(packets),
                     sorted(reads)[:8], sorted(writes)[:8], NAMES.get(f, '')))
    return rows

if __name__ == '__main__':
    rows = main()
    out = None
    if '--markdown' in sys.argv:
        out = open(sys.argv[sys.argv.index('--markdown') + 1], 'w', encoding='utf-8', newline='\n')
    lines = ['# The D3D library in default.xex', '',
             'Generated by `scripts/d3d_api.py`. The functions of the linked-in Xbox 360 D3D (0x822E0000..0x82300000)',
             'that the game calls from outside the library: the API the port takes over at the D3D level',
             '(see [native-d3d11-plan.md](native-d3d11-plan.md)). "r3 reads/writes" are offsets of the first',
             'argument the function touches; for a device function, the device\'s fields.', '',
             f'{len(rows)} functions.', '',
             '| function | instr. | calls | callers | PM4 written | r3 reads | r3 writes | name |',
             '| --- | --- | --- | --- | --- | --- | --- | --- |']
    for f, size, calls, nc, packets, reads, writes, name in rows:
        lines.append(f'| `sub_{f:08X}` | {size} | {calls} | {nc} | {", ".join(packets)} | {" ".join(map(str, reads))} | {" ".join(map(str, writes))} | {name} |')
    text = '\n'.join(lines) + '\n'
    if out: out.write(text); out.close(); print(f'{len(rows)} functions written')
    else: print(text)
