"""Generates one host stub per Xbox 360 kernel import the guest needs.

Reads docs/kernel-imports.txt (produced by `CoD3Scan <xex> --imports`) and
writes CoD3Host/kernel_stubs.cpp plus a name list used for reporting.

Run from the repository root:  python scripts/gen_import_stubs.py
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
IMPORTS = ROOT / "docs" / "kernel-imports.txt"
HOST = ROOT / "CoD3Host"
IMPLEMENTED = HOST / "implemented_imports.txt"

HEADER = """// Generated by scripts/gen_import_stubs.py from docs/kernel-imports.txt.
// Do not edit by hand: regenerate.
//
// One stub per kernel import that does not have a real implementation yet.
// Each reports itself and stops the process. To implement one: write it in the
// kernel_*.cpp file for its area, add its name to implemented_imports.txt, and
// regenerate. Running the game then tells you the next one it needs.
//
// PPC_FUNC, not PPC_FUNC_IMPL: ppc_recomp_shared.h declares the __imp__ name
// of an import with C++ linkage, and a definition has to match that. The
// PPC_FUNC_IMPL form is for recompiled guest functions, whose __imp__ symbol
// is a separate C linkage name behind an alias.
#include "kernel.h"

"""


def main() -> int:
    if not IMPORTS.is_file():
        print(f"missing {IMPORTS}", file=sys.stderr)
        return 1

    names = sorted({
        line.split()[1]
        for line in IMPORTS.read_text(encoding="ascii").splitlines()
        if len(line.split()) == 2
    })
    if not names:
        print("no imports parsed", file=sys.stderr)
        return 1

    # Imports with a real implementation must not also get a stub, or the two
    # definitions collide at link time.
    implemented = set()
    if IMPLEMENTED.is_file():
        for line in IMPLEMENTED.read_text(encoding="ascii").splitlines():
            line = line.split("#", 1)[0].strip()
            if line:
                implemented.add(line)

    unknown = implemented - set(names)
    if unknown:
        print("listed as implemented but not an import of this XEX: " +
              ", ".join(sorted(unknown)), file=sys.stderr)
        return 1

    stubbed = [n for n in names if n not in implemented]

    HOST.mkdir(exist_ok=True)
    (HOST / "kernel_stubs.cpp").write_text(
        HEADER + "\n".join(
            f'PPC_FUNC(__imp__{n}) {{ Kernel::Unimplemented("{n}", ctx, base); }}'
            for n in stubbed
        ) + "\n",
        encoding="ascii",
    )
    # Name to host function, so the loader can put each import thunk into the
    # indirect call table. The guest reaches some kernel calls through a
    # function pointer rather than a direct branch, and those go through the
    # table; without an entry the pointer is null and the process dies with no
    # explanation.
    (HOST / "kernel_import_table.inc").write_text(
        "// Generated by scripts/gen_import_stubs.py. Import name to host stub.\n" +
        "\n".join(f'{{ "{n}", __imp__{n} }},' for n in names) + "\n",
        encoding="ascii",
    )
    print(f"{len(names)} kernel imports: {len(implemented)} implemented, "
          f"{len(stubbed)} still stubs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
